# Generated by Django 4.0.5 on 2022-07-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlcrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(max_length=20),
        ),
    ]
